Repository AzureAD/microsoft-authentication-library-for-dotnet, pull requests merged in 2020-10, with the labels that each got.

#2088 Update PublicClientApplicationBuilder.cs
  src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
Labels: documentation

#2096 Fix AuthenticationResult ctor
  src/client/Microsoft.Identity.Client/AuthenticationResult.cs
  tests/Microsoft.Identity.Test.Unit/PublicApiTests/AccountIdTest.cs
  tests/Microsoft.Identity.Test.Unit/PublicApiTests/AuthenticationResultTests.cs
  tests/Microsoft.Identity.Test.Unit/PublicApiTests/LoggerTests.cs
Labels: P2, bug

#2103 Update the changelog to 4.20.1
  changelog.txt
Labels: In Progress
